// bairros.js — Lista dos 200 bairros do Desentupi Pro
// Cada bairro tem slug (URL), nome de exibição, região, cidade

window.BAIRROS = [
  // ── ZONA LESTE ──
  { slug: 'tatuape', nome: 'Tatuapé', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'mooca', nome: 'Mooca', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'penha', nome: 'Penha', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'itaquera', nome: 'Itaquera', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'aricanduva', nome: 'Aricanduva', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'belem', nome: 'Belém', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'bras', nome: 'Brás', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'vila-formosa', nome: 'Vila Formosa', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'vila-carrao', nome: 'Vila Carrão', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'vila-prudente', nome: 'Vila Prudente', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'sao-mateus', nome: 'São Mateus', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'ermelino-matarazzo', nome: 'Ermelino Matarazzo', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'vila-matilde', nome: 'Vila Matilde', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'cangaiba', nome: 'Cangaíba', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'patriarca', nome: 'Patriarca', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'sapopemba', nome: 'Sapopemba', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'itaim-paulista', nome: 'Itaim Paulista', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'guaianases', nome: 'Guaianases', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'cidade-tiradentes', nome: 'Cidade Tiradentes', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'analia-franco', nome: 'Anália Franco', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'vila-esperanca', nome: 'Vila Esperança', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'vila-ema', nome: 'Vila Ema', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'vila-california', nome: 'Vila Califórnia', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'agua-rasa', nome: 'Água Rasa', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'alto-da-mooca', nome: 'Alto da Mooca', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'parque-sao-lucas', nome: 'Parque São Lucas', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'vila-bertioga', nome: 'Vila Bertioga', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'sao-miguel-paulista', nome: 'São Miguel Paulista', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'vila-jacui', nome: 'Vila Jacuí', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'jardim-brasil-leste', nome: 'Jardim Brasil', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'carrao', nome: 'Carrão', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'jardim-textil', nome: 'Jardim Têxtil', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'vila-antonieta', nome: 'Vila Antonieta', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'cidade-patriarca', nome: 'Cidade Patriarca', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'vila-granada', nome: 'Vila Granada', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'iguatemi', nome: 'Iguatemi', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'lajeado', nome: 'Lajeado', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'jardim-helena', nome: 'Jardim Helena', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'vila-curuca', nome: 'Vila Curuçá', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'jardim-romano', nome: 'Jardim Romano', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'jardim-robru', nome: 'Jardim Robru', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'parque-do-carmo', nome: 'Parque do Carmo', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'artur-alvim', nome: 'Artur Alvim', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'cidade-lider', nome: 'Cidade Líder', regiao: 'Zona Leste', cidade: 'São Paulo' },
  { slug: 'jardim-popular', nome: 'Jardim Popular', regiao: 'Zona Leste', cidade: 'São Paulo' },

  // ── ZONA SUL ──
  { slug: 'vila-mariana', nome: 'Vila Mariana', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'moema', nome: 'Moema', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'saude', nome: 'Saúde', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'jabaquara', nome: 'Jabaquara', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'ipiranga', nome: 'Ipiranga', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'sacoma', nome: 'Sacomã', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'cursino', nome: 'Cursino', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'santo-amaro', nome: 'Santo Amaro', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'campo-belo', nome: 'Campo Belo', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'brooklin', nome: 'Brooklin', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'morumbi', nome: 'Morumbi', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'capao-redondo', nome: 'Capão Redondo', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'cidade-ademar', nome: 'Cidade Ademar', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'campo-limpo', nome: 'Campo Limpo', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'vila-andrade', nome: 'Vila Andrade', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'pedreira', nome: 'Pedreira', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'interlagos', nome: 'Interlagos', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'grajau', nome: 'Grajaú', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'parelheiros', nome: 'Parelheiros', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'cidade-dutra', nome: 'Cidade Dutra', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'socorro', nome: 'Socorro', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'jardim-sao-luis', nome: 'Jardim São Luís', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'jardim-angela', nome: 'Jardim Ângela', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'vila-sonia', nome: 'Vila Sônia', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'real-parque', nome: 'Real Parque', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'vila-olimpia', nome: 'Vila Olímpia', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'chacara-klabin', nome: 'Chácara Klabin', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'aclimacao', nome: 'Aclimação', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'cambuci', nome: 'Cambuci', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'vila-clementino', nome: 'Vila Clementino', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'vila-nova-conceicao', nome: 'Vila Nova Conceição', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'itaim-bibi', nome: 'Itaim Bibi', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'vila-gertrudes', nome: 'Vila Gertrudes', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'vila-cordeiro', nome: 'Vila Cordeiro', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'veleiros', nome: 'Veleiros', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'aeroporto-congonhas', nome: 'Aeroporto Congonhas', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'jurubatuba', nome: 'Jurubatuba', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'cidade-vargas', nome: 'Cidade Vargas', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'americanopolis', nome: 'Americanópolis', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'vila-guarani', nome: 'Vila Guarani', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'vila-do-encontro', nome: 'Vila do Encontro', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'cidade-julia', nome: 'Cidade Júlia', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'vila-mascote', nome: 'Vila Mascote', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'pirajussara', nome: 'Pirajussara', regiao: 'Zona Sul', cidade: 'São Paulo' },
  { slug: 'capela-do-socorro', nome: 'Capela do Socorro', regiao: 'Zona Sul', cidade: 'São Paulo' },

  // ── ZONA NORTE ──
  { slug: 'santana', nome: 'Santana', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'tucuruvi', nome: 'Tucuruvi', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'tremembe', nome: 'Tremembé', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'jacana', nome: 'Jaçanã', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'vila-maria', nome: 'Vila Maria', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'vila-guilherme', nome: 'Vila Guilherme', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'casa-verde', nome: 'Casa Verde', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'cachoeirinha', nome: 'Cachoeirinha', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'limao', nome: 'Limão', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'mandaqui', nome: 'Mandaqui', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'freguesia-do-o', nome: 'Freguesia do Ó', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'brasilandia', nome: 'Brasilândia', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'pirituba', nome: 'Pirituba', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'perus', nome: 'Perus', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'jaragua', nome: 'Jaraguá', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'vila-medeiros', nome: 'Vila Medeiros', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'imirim', nome: 'Imirim', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'parada-inglesa', nome: 'Parada Inglesa', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'jardim-sao-paulo', nome: 'Jardim São Paulo', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'vila-sabrina', nome: 'Vila Sabrina', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'lauzane-paulista', nome: 'Lauzane Paulista', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'vila-nova-cachoeirinha', nome: 'Vila Nova Cachoeirinha', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'vila-maria-alta', nome: 'Vila Maria Alta', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'tucuruvi-alto', nome: 'Tucuruvi Alto', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'anhanguera', nome: 'Anhanguera', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'parque-edu-chaves', nome: 'Parque Edu Chaves', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'vila-galvao-norte', nome: 'Vila Galvão', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'carandiru', nome: 'Carandiru', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'vila-aurora', nome: 'Vila Aurora', regiao: 'Zona Norte', cidade: 'São Paulo' },
  { slug: 'jardim-tremembe', nome: 'Jardim Tremembé', regiao: 'Zona Norte', cidade: 'São Paulo' },

  // ── ZONA OESTE ──
  { slug: 'pinheiros', nome: 'Pinheiros', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'vila-madalena', nome: 'Vila Madalena', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'lapa', nome: 'Lapa', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'perdizes', nome: 'Perdizes', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'barra-funda', nome: 'Barra Funda', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'butanta', nome: 'Butantã', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'alto-de-pinheiros', nome: 'Alto de Pinheiros', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'jardim-paulista', nome: 'Jardim Paulista', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'vila-leopoldina', nome: 'Vila Leopoldina', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'jaguare', nome: 'Jaguaré', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'rio-pequeno', nome: 'Rio Pequeno', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'raposo-tavares', nome: 'Raposo Tavares', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'sumare', nome: 'Sumaré', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'pacaembu', nome: 'Pacaembu', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'higienopolis', nome: 'Higienópolis', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'vila-romana', nome: 'Vila Romana', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'pompeia', nome: 'Pompéia', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'agua-branca', nome: 'Água Branca', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'vila-anastacio', nome: 'Vila Anastácio', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'jaguara', nome: 'Jaguara', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'jardim-bonfiglioli', nome: 'Jardim Bonfiglioli', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'city-lapa', nome: 'City Lapa', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'vila-ipojuca', nome: 'Vila Ipojuca', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'cidade-universitaria', nome: 'Cidade Universitária', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'vila-hamburguesa', nome: 'Vila Hamburguesa', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'jaguare-velho', nome: 'Jaguaré Velho', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'vila-indiana', nome: 'Vila Indiana', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'caxingui', nome: 'Caxingui', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'jardim-peri-peri', nome: 'Jardim Peri-Peri', regiao: 'Zona Oeste', cidade: 'São Paulo' },
  { slug: 'vila-sonia-oeste', nome: 'Vila Sônia (Oeste)', regiao: 'Zona Oeste', cidade: 'São Paulo' },

  // ── CENTRO ──
  { slug: 'centro-historico', nome: 'Centro Histórico', regiao: 'Centro', cidade: 'São Paulo' },
  { slug: 'se', nome: 'Sé', regiao: 'Centro', cidade: 'São Paulo' },
  { slug: 'republica', nome: 'República', regiao: 'Centro', cidade: 'São Paulo' },
  { slug: 'bela-vista', nome: 'Bela Vista', regiao: 'Centro', cidade: 'São Paulo' },
  { slug: 'liberdade', nome: 'Liberdade', regiao: 'Centro', cidade: 'São Paulo' },
  { slug: 'consolacao', nome: 'Consolação', regiao: 'Centro', cidade: 'São Paulo' },
  { slug: 'santa-cecilia', nome: 'Santa Cecília', regiao: 'Centro', cidade: 'São Paulo' },
  { slug: 'bom-retiro', nome: 'Bom Retiro', regiao: 'Centro', cidade: 'São Paulo' },
  { slug: 'pari', nome: 'Pari', regiao: 'Centro', cidade: 'São Paulo' },
  { slug: 'glicerio', nome: 'Glicério', regiao: 'Centro', cidade: 'São Paulo' },

  // ── ABC — SANTO ANDRÉ ──
  { slug: 'santo-andre-centro', nome: 'Santo André Centro', regiao: 'ABC', cidade: 'Santo André' },
  { slug: 'santo-andre-jardim', nome: 'Jardim', regiao: 'ABC', cidade: 'Santo André' },
  { slug: 'santo-andre-campestre', nome: 'Campestre', regiao: 'ABC', cidade: 'Santo André' },
  { slug: 'santo-andre-vila-assuncao', nome: 'Vila Assunção', regiao: 'ABC', cidade: 'Santo André' },
  { slug: 'santo-andre-vila-bastos', nome: 'Vila Bastos', regiao: 'ABC', cidade: 'Santo André' },
  { slug: 'santo-andre-utinga', nome: 'Utinga', regiao: 'ABC', cidade: 'Santo André' },
  { slug: 'santo-andre-vila-principe-gales', nome: 'Vila Príncipe de Gales', regiao: 'ABC', cidade: 'Santo André' },
  { slug: 'santo-andre-paranapiacaba', nome: 'Paranapiacaba', regiao: 'ABC', cidade: 'Santo André' },

  // ── ABC — SÃO BERNARDO DO CAMPO ──
  { slug: 'sao-bernardo-centro', nome: 'São Bernardo Centro', regiao: 'ABC', cidade: 'São Bernardo do Campo' },
  { slug: 'sao-bernardo-rudge-ramos', nome: 'Rudge Ramos', regiao: 'ABC', cidade: 'São Bernardo do Campo' },
  { slug: 'sao-bernardo-nova-petropolis', nome: 'Nova Petrópolis', regiao: 'ABC', cidade: 'São Bernardo do Campo' },
  { slug: 'sao-bernardo-bairro-assuncao', nome: 'Bairro Assunção', regiao: 'ABC', cidade: 'São Bernardo do Campo' },
  { slug: 'sao-bernardo-jardim-do-mar', nome: 'Jardim do Mar', regiao: 'ABC', cidade: 'São Bernardo do Campo' },
  { slug: 'sao-bernardo-anchieta', nome: 'Anchieta', regiao: 'ABC', cidade: 'São Bernardo do Campo' },
  { slug: 'sao-bernardo-baeta-neves', nome: 'Baeta Neves', regiao: 'ABC', cidade: 'São Bernardo do Campo' },
  { slug: 'sao-bernardo-riacho-grande', nome: 'Riacho Grande', regiao: 'ABC', cidade: 'São Bernardo do Campo' },

  // ── ABC — SÃO CAETANO ──
  { slug: 'sao-caetano-centro', nome: 'São Caetano Centro', regiao: 'ABC', cidade: 'São Caetano do Sul' },
  { slug: 'sao-caetano-barcelona', nome: 'Barcelona', regiao: 'ABC', cidade: 'São Caetano do Sul' },
  { slug: 'sao-caetano-santa-paula', nome: 'Santa Paula', regiao: 'ABC', cidade: 'São Caetano do Sul' },
  { slug: 'sao-caetano-ceramica', nome: 'Cerâmica', regiao: 'ABC', cidade: 'São Caetano do Sul' },
  { slug: 'sao-caetano-olimpico', nome: 'Olímpico', regiao: 'ABC', cidade: 'São Caetano do Sul' },

  // ── ABC — DIADEMA ──
  { slug: 'diadema-centro', nome: 'Diadema Centro', regiao: 'ABC', cidade: 'Diadema' },
  { slug: 'diadema-eldorado', nome: 'Eldorado', regiao: 'ABC', cidade: 'Diadema' },
  { slug: 'diadema-campanario', nome: 'Campanário', regiao: 'ABC', cidade: 'Diadema' },
  { slug: 'diadema-piraporinha', nome: 'Piraporinha', regiao: 'ABC', cidade: 'Diadema' },

  // ── ABC — MAUÁ ──
  { slug: 'maua-centro', nome: 'Mauá Centro', regiao: 'ABC', cidade: 'Mauá' },
  { slug: 'maua-jardim-zaira', nome: 'Jardim Zaíra', regiao: 'ABC', cidade: 'Mauá' },
  { slug: 'maua-vila-assis-brasil', nome: 'Vila Assis Brasil', regiao: 'ABC', cidade: 'Mauá' },

  // ── ABC — RIBEIRÃO PIRES ──
  { slug: 'ribeirao-pires-centro', nome: 'Ribeirão Pires Centro', regiao: 'ABC', cidade: 'Ribeirão Pires' },

  // ── ABC — RIO GRANDE DA SERRA ──
  { slug: 'rio-grande-da-serra-centro', nome: 'Rio Grande da Serra Centro', regiao: 'ABC', cidade: 'Rio Grande da Serra' },

  // ── OUTRAS CIDADES METROPOLITANAS ──
  { slug: 'guarulhos-centro', nome: 'Guarulhos Centro', regiao: 'Grande SP', cidade: 'Guarulhos' },
  { slug: 'guarulhos-vila-galvao', nome: 'Vila Galvão (Guarulhos)', regiao: 'Grande SP', cidade: 'Guarulhos' },
  { slug: 'guarulhos-macedo', nome: 'Macedo', regiao: 'Grande SP', cidade: 'Guarulhos' },
  { slug: 'guarulhos-picanco', nome: 'Picanço', regiao: 'Grande SP', cidade: 'Guarulhos' },
  { slug: 'osasco-centro', nome: 'Osasco Centro', regiao: 'Grande SP', cidade: 'Osasco' },
  { slug: 'osasco-vila-yara', nome: 'Vila Yara', regiao: 'Grande SP', cidade: 'Osasco' },
  { slug: 'barueri-alphaville', nome: 'Alphaville', regiao: 'Grande SP', cidade: 'Barueri' },
  { slug: 'carapicuiba-centro', nome: 'Carapicuíba Centro', regiao: 'Grande SP', cidade: 'Carapicuíba' },
  { slug: 'taboao-da-serra-centro', nome: 'Taboão da Serra', regiao: 'Grande SP', cidade: 'Taboão da Serra' },
  { slug: 'cotia-centro', nome: 'Cotia Centro', regiao: 'Grande SP', cidade: 'Cotia' },
];

// Função para encontrar bairro pelo slug
window.findBairro = function(slug) {
  return window.BAIRROS.find(b => b.slug === slug);
};
